DROP TABLE IF EXISTS `brands`;
DROP TABLE IF EXISTS `foods`;
DROP TABLE IF EXISTS `recipes`;
DROP TABLE IF EXISTS `recipe_ingredients`;
DROP TABLE IF EXISTS `recipe_steps`;
DROP TABLE IF EXISTS `tags`;
DROP TABLE IF EXISTS `recipe_tags`;