CREATE TABLE IF NOT EXISTS `brand` (
  `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(255) NOT NULL UNIQUE,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `food` (
  `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(255) NOT NULL UNIQUE,
  `brand_id` INT NOT NULL REFERENCES `brand`(`id`),
  `calories` INT NOT NULL,
  `protein` INT NOT NULL,
  `carbs` INT NOT NULL,
  `sugar` INT NOT NULL,
  `fat` INT NOT NULL,
  `saturated_fat` INT NULL,
  `fiber` INT NULL,
  `sodium` INT NULL,
  `image_url` VARCHAR(255) NOT NULL,
  `category` VARCHAR(50) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP
);